name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  format_check:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install black flake8

    - name: Check formatting with Black
      run: |
        black . --line-length 79 --check  # This will check without formatting

    - name: Run Flake8
      run: |
        flake8 --max-line-length=79
