name: Python Linting

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install Black and Flake8
        run: |
          python -m pip install black flake8

      - name: Run Black to format code
        run: black . --line-length 79 --quiet  # Auto-formats code with Black

      - name: Run Flake8 to check code style
        run: flake8 . --max-line-length=79  # Ensures Flake8 passes
        continue-on-error: true 